"""add findings table

Revision ID: 193999690bd2
Revises: 08e3b07c32ee
Create Date: 2026-04-28 18:31:00.052959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193999690bd2'
down_revision: Union[str, None] = '08e3b07c32ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_analysis_id'), 'findings', ['analysis_id'], unique=False)
    op.alter_column('analyses', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('analyses', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_analyses_project_id'), 'analyses', ['project_id'], unique=False)
    op.drop_constraint(op.f('analyses_project_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_project_id_fkey'), 'analyses', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_analyses_project_id'), table_name='analyses')
    op.alter_column('analyses', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('analyses', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_findings_analysis_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
